export const GET_MESSAGES_REQUEST = "GET_MESSAGE_REQUEST";
export const GET_MESSAGES_SUCCESS = "GET_MESSAGE_SUCCESS";
export const GET_MESSAGES_FAIL = "GET_MESSAGE_FAIL";

export const CREATE_MESSAGE_REQUEST = "CREATE_MESSAGE_REQUEST";
export const CREATE_MESSAGE_SUCCESS = "CREATE_MESSAGE_SUCCESS";
export const CREATE_MESSAGE_FAIL = "CREATE_MESSAGE_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
