export const GET_ALL_NOTIFY_REQUEST = "GET_ALL_NOTIFY_REQUEST";
export const GET_ALL_NOTIFY_SUCCESS = "GET_ALL_NOTIFY_SUCCESS";
export const GET_ALL_NOTIFY_FAIL = "GET_ALL_NOTIFY_FAIL";

export const CREATE_NOTIFY_REQUEST = "CREATE_NOTIFY_REQUEST";
export const CREATE_NOTIFY_SUCCESS = "CREATE_NOTIFY_SUCCESS";
export const CREATE_NOTIFY_FAIL = "CREATE_NOTIFY_FAIL";

export const UPDATE_NOTIFY_REQUEST = "UPDATE_NOTIFY_REQUEST";
export const UPDATE_NOTIFY_SUCCESS = "UPDATE_NOTIFY_SUCCESS";
export const UPDATE_NOTIFY_FAIL = "UPDATE_NOTIFY_FAIL";

export const READ_NOTIFY_REQUEST = "READ_NOTIFY_REQUEST";
export const READ_NOTIFY_RESET = "READ_NOTIFY_RESET";
export const READ_NOTIFY_SUCCESS = "READ_NOTIFY_SUCCESS";
export const READ_NOTIFY_FAIL = "READ_NOTIFY_FAIL";

export const SEND_CHAT_REQUEST = "SEND_CHAT_REQUEST";
export const SEND_CHAT_RESET = "SEND_CHAT_RESET";
export const SEND_CHAT_SUCCESS = "SEND_CHAT_SUCCESS";
export const SEND_CHAT_FAIL = "SEND_CHAT_FAIL";

export const ACCEPT_CHAT_REQUEST = "ACCEPT_CHAT_REQUEST";
export const ACCEPT_CHAT_RESET = "ACCEPT_CHAT_RESET";
export const ACCEPT_CHAT_SUCCESS = "ACCEPT_CHAT_SUCCESS";
export const ACCEPT_CHAT_FAIL = "ACCEPT_CHAT_FAIL";

export const DENIED_CHAT_REQUEST = "DENIED_CHAT_REQUEST";
export const DENIED_CHAT_RESET = "DENIED_CHAT_RESET";
export const DENIED_CHAT_SUCCESS = "DENIED_CHAT_SUCCESS";
export const DENIED_CHAT_FAIL = "DENIED_CHAT_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
