export const LOGIN_REQUSET = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGIN_RESET = "LOGIN_RESET";

export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILURE = "GET_USER_FAILURE";

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_RESET = "UPDATE_USER_RESET";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";

export const UPDATE_PASSWORD_USER_REQUEST = "UPDATE_PASSWORD_USER_REQUEST";
export const UPDATE_PASSWORD_USER_SUCCESS = "UPDATE_PASSWORD_USER_SUCCESS";
export const UPDATE_PASSWORD_USER_RESET = "UPDATE_PASSWORD_USER_RESET";
export const UPDATE_PASSWORD_USER_FAIL = "UPDATE_PASSWORD_USER_FAIL";

export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
